name = "nphilipp/hello-world"
version = "0.0.0"
compiler = "v1.1.13"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'nphilipp/hello-world'"

[repository]
user = "nphilipp"
project = "hello-world"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
